name: CI_CD Pipeline
on:
  workflow_dispatch:
        inputs:
            env:
                description: Environment
                required: true
                type: choice
                options:
                    - prod
                    - stage
                    - dev
                    - uat 

jobs:
  Build:
    
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: checkout
      uses: 'actions/checkout@v4'

    - name: GCP authenticate
      uses: 'google-github-actions/auth@v3'
      with:
        project_id: '${{secrets.PROJECT_ID}}'
        workload_identity_provider: '${{secrets.CI_CD_WORKLOAD_IDENTITY_PROVIDER}}'
        service_account: ${{secrets.CI_CD_SA}}
    - name: Configure docker for Artifact Registry
      run: |
        gcloud --quiet auth configure-docker me-central1-docker.pkg.dev

    - name: build image
      run: |
        cd ./app
        IMAGE="me-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/simple-web-app/simple_app:v1"
        docker build -t $IMAGE .

    - name: Push image
      run: |
        IMAGE="me-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/simple-web-app/simple_app:v1"
        docker push $IMAGE


  Deploy:
    
    runs-on: ubuntu-latest
    needs: build

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: checkout
      uses: 'actions/checkout@v4'

    - name: GCP authenticate
      uses: 'google-github-actions/auth@v3'
      with:
        project_id: '${{secrets.PROJECT_ID}}'
        workload_identity_provider: '${{secrets.CI_CD_WORKLOAD_IDENTITY_PROVIDER}}'
        service_account: ${{secrets.CI_CD_SA}}

    - name: Deploy new image to Cloud Run
      run: |
        IMAGE="me-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/simple-web-app/simple_app:v1"
        gcloud run services update ${{inputs.env}}-simple-web-app \
        --image=$IMAGE \
        --region="me-central1" \
        --project=${{ secrets.PROJECT_ID }}