name: CI_CD Pipeline
on:
  workflow_dispatch:  

jobs:
  build:
    
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: checkout
      uses: 'actions/checkout@v4'

    - name: GCP authenticate
      uses: 'google-github-actions/auth@v3'
      with:
        project_id: '${{secrets.PROJECT_ID}}'
        workload_identity_provider: '${{secrets.CI_CD_WORKLOAD_IDENTITY_PROVIDER}}'
        service_account: ${{secrets.CI_CD_SA}}
    - name: Configure docker for Artifact Registry
      run: |
        gcloud --quiet auth configure-docker me-central1-docker.pkg.dev

    - name: build image
      run: |
        IMAGE=me-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/simple-web-app/simple_app:v1"
        docker build -t $IMAGE .

    - name: Push image
      run: |
        docker push $IMAGE