name: Infrastructure Pipeline
on:
  push:
    branches:
      - 'main'  

jobs:
  build:
    
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: checkout
      uses: 'actions/checkout@v4'

    - name: Dump GitHub OIDC token claims
      run: |
        set -e
        TOKEN=$(curl -sSL \
        -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
        "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=foo")
         IDTOKEN=$(echo $TOKEN | jq -r '.value')
        echo "Full token: $IDTOKEN"
        echo "Decoded claims:"
        echo $IDTOKEN | cut -d '.' -f2 | base64 -d 2>/dev/null | jq

    - name: GCP authenticate
      uses: 'google-github-actions/auth@v3'
      with:
        project_id: '${{secrets.PROJECT_ID}}'
        workload_identity_provider: '${{secrets.CI_CD_WORKLOAD_IDENTITY_PROVIDER}}'
        service_account: ${{secrets.CI_CD_SA}}
        