name: Infrastructure Pipeline
on:
  workflow_dispatch:
        inputs:
            env:
                description: Environment
                required: true
                type: choice
                options:
                    - prod
                    - stage
                    - dev
                    - uat

jobs:
  build_infra:
    
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: checkout
      uses: 'actions/checkout@v4'

    - name: Dump GitHub OIDC token claims
      run: |
        set -e
        TOKEN=$(curl -sSL \
        -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
        "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=foo")
         IDTOKEN=$(echo $TOKEN | jq -r '.value')
        echo "Full token: $IDTOKEN"
        echo "Decoded claims:"
        echo $IDTOKEN | cut -d '.' -f2 | base64 -d 2>/dev/null | jq

    - name: GCP authenticate
      uses: 'google-github-actions/auth@v3'
      with:
        project_id: '${{secrets.PROJECT_ID}}'
        workload_identity_provider: '${{secrets.TERRAFORM_WORKLOAD_IDENTITY_PROVIDER}}'
        service_account: ${{secrets.TERRAFORM_SA}}
        
    - name: setup-terraform
      uses: hashicorp/setup-terraform@v3

    - name: terraform Init
      run: |
          cd ./terraform/
          terraform init -backend-config="../conf/${{inputs.env}}_backend.hcl" 
    
    - name: Terraform apply
      run: |
          cd ./terraform/
          terraform apply   -var="project_id=${{secrets.PROJECT_ID}}" -var-file="../conf/${{inputs.env}}.tfvars" --auto-approve
