name: Infrastructure Pipeline
on:
  workflow_dispatch:
        inputs:
            env:
                description: Environment
                required: true
                type: choice
                options:
                    - prod
                    - stage
                    - dev
                    - qa

jobs:
  build_infra:
    
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: checkout
      uses: 'actions/checkout@v4'

    - name: GCP authenticate
      uses: 'google-github-actions/auth@v3'
      with:
        project_id: 'simple-web-app-473205'
        workload_identity_provider: 'projects/460540992837/locations/global/workloadIdentityPools/terraform-simple-app-pool/providers/github-provider'
        token_format: access_token
    run: |
        cat /home/runner/work/simple_web_app/simple_web_app/gha-creds-d5b2c48dfd77856a.json


    - name: setup-terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: |
          cd ./Terraform/main
          terraform init 
    # -backend-config="../conf/${{inputs.env}}_backend_conf.hcl" 
    
    - name: Terraform apply
      run: |
          cd ./Terraform/main  
          terraform apply 
    # -var-file="../conf/${{inputs.env}}.tfvars"  --auto-approve
